#include "Stepper.h"
#include "../../LIB/UTILES.h"
#include "../../MCAL/GPIO/GPIO.h"
#include <util/delay.h>

static UINT8 motor_direction = MOTOR_DIRECTION;
static UINT8 delay_ms = 100;


void Stepper_Init(){

#if MOTOR_TYPE == UNIPOLAR
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN0, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN1, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN2, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN3, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN4, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,PIN5, OUTPUT);

#elif MOTOR_TYPE == BIPOLAR
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_A, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_B, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_C, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_D, OUTPUT);

#elif MOTOR_TYPE == UNIVERSAL

	GPIO_INIT_PORT_DIRECTION(MOTOR_PORT,OUTPUT);

#endif

}


void Stepper_SetSpeed(UINT8 speed){
	delay_ms = (1/((STEPS_PER_REVOLUTION * speed)/60))*1000 ; // time in ms

}




void Stepper_SetDirection(UINT8 direction){

	switch(direction){
	case CLOCKWISE:
		motor_direction = CLOCKWISE;
		break;
	case COUNTER_CLOCKWISE:
		motor_direction = COUNTER_CLOCKWISE;
		break;
	}


}

static void Stepper_One_Step_Clockwise(void){

	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,HIGH);
	_delay_ms(delay_ms);



}

static void Stepper_One_Step_CounterClockwise(void){
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,HIGH);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_A,HIGH);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_B,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_C,LOW);
	GPIO_WRITE_PIN_VALUE(MOTOR_PORT,WINDING_D,LOW);
	_delay_ms(delay_ms);


}

void Stepper_Half_Revoloution(){

}

void Stepper_Full_Revoloution(){


}


#if MOTOR_TYPE == BIPOLAR
void Stepper_Steps(UINT8 steps){
	UINT8 i ;

	if(motor_direction == CLOCKWISE){

		for(i = 0;i<steps;i++)
		  Stepper_One_Step_Clockwise();
		}
   else if(motor_direction == COUNTER_CLOCKWISE){
		for(i = 0;i<steps;i++)
		  Stepper_One_Step_CounterClockwise();
		}
}


#elif MOTOR_TYPE == UNIPOLAR
void Stepper_Step(UINT8 steps){

}


#elif MOTOR_TYPE == UNIVERSAL
void Stepper_Step(UINT8 steps){}


#endif



