#include "Stepper.h"
static UINT8 DELAY_TIME = 100;// to be able to change time in (ms)

static UINT8 motor_direction = MOTOR_DIRECTION;


void Stepper_Init(){
#if MOTOR_TYPE == UNIPOLAR
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_A, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_B, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_C, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_D, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_E, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_F, OUTPUT);

#elif MOTOR_TYPE == BIPOLAR
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_A, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_B, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_C, OUTPUT);
	 GPIO_INIT_PIN_DIRECTION(MOTOR_PORT ,WINDING_D, OUTPUT);

#elif MOTOR_TYPE == UNIVERSAL

	GPIO_INIT_PORT_DIRECTION(MOTOR_PORT,OUTPUT);

#endif

GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN0, OUTPUT);
GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN1, OUTPUT);
GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN2, OUTPUT);
GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN3, OUTPUT);
GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN4, OUTPUT);
GPIO_INIT_PIN_DIRECTION (MOTOR_PORT, PIN5, OUTPUT);

  

}


void Stepper_SetSpeed(UINT8 speed)
{
	DELAY_TIME = (1/((STEPS_PER_REVOLUTION * speed)/60))*1000 ; // time in ms


}

void Stepper_SetDirection(UINT8 direction){
	switch(direction){
	case CLOCKWISE:
		motor_direction = CLOCKWISE;
		break;
	case COUNTER_CLOCKWISE:
		motor_direction = COUNTER_CLOCKWISE;
		break;
	}

}


void Stepper_Steps(UINT8 steps){


}

