#include "Keypad.h"
#include "Keypad_Config.h"


static const UINT8 keypad_array[4][4] =  { KEYPAD_ARRAY };


void Keypad_Init(void){
  
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R1_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R2_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R3_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R4_PIN, OUTPUT);

	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R1_PIN, type_of_connection);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R2_PIN, type_of_connection);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R3_PIN, type_of_connection);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R4_PIN, type_of_connection);

	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C1_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C2_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C3_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C4_PIN, INPUT);

}


}


UINT8 Keypad_GetKey(void){



}
