#include "Keypad.h"
#include "Keypad_Config.h"
#include<util/delay.h>

static const UINT8 keypad_array[ROW][COL] =  { KEYPAD_ARRAY };   //more readable


void Keypad_Init(void){
  
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R1_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R2_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R3_PIN, OUTPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, R4_PIN, OUTPUT);

	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R1_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R2_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R3_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, R4_PIN, HIGH);

	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C1_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C2_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C3_PIN, INPUT);
	GPIO_INIT_PIN_DIRECTION(KEYPAD_PORT, C4_PIN, INPUT);
	
	//Using Internal Pull Up 
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, C1_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, C2_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, C3_PIN, HIGH);
	GPIO_WRITE_PIN_VALUE(KEYPAD_PORT, C4_PIN, HIGH);

}





UINT8 Keypad_GetKey(void)
{
  UINT8 ROWCOUNT;
	UINT8 COLCOUNT;
	UINT8 RESULT=0;
	for(ROWCOUNT=ROW_INT; ROWCOUNT<=ROW_END ;ROWCOUNT++)
	{
		GPIO_WRITE_PIN_VALUE(KEYPAD_PORT ,ROWCOUNT , LOW);
		for (COLCOUNT=COL_INT ;COLCOUNT<=COL_END ;COLCOUNT++)
		{
			if(GPIO_READ_PIN_VALUE(KEYPAD_PORT,COLCOUNT)==LOW)
			{
				RESULT=keypad_array[ROWCOUNT-ROW_INT][COLCOUNT-COL_INT];
				 /* because we don't use timer we use this condition for one press */
				while(GPIO_READ_PIN_VALUE(KEYPAD_PORT,COLCOUNT)==LOW);
				
				_delay_ms(10);  //to avoid bouncing
			}
			
		}
    
		GPIO_WRITE_PIN_VALUE(KEYPAD_PORT ,ROWCOUNT , HIGH);  //deactivate again
	}

   return RESULT;


}
